In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame().dtypes

Series([], dtype: object)

In [ ]:
pd.DataFrame(data, columns=["Numeros"], index= ["lun"])

In [ ]:
data =(["Juan", 20], ["Luisa", 30], ["Rciardo", 25])
pd.DataFrame(data, columns = ["nombre", "edad"])

    nombre  edad
0     Juan    20
1    Luisa    30
2  Rciardo    25

In [ ]:
data = {"NOMBRE":["jUAN", "LUISA", "ricardo"],
          "edad":[20, 30, 25],
        "sexo":["h","m","h"]}
pd.DataFrame(data)

    NOMBRE  edad sexo
0     jUAN    20    h
1    LUISA    30    m
2  ricardo    25    h

si son archivos temporales

In [ ]:
df = pd.read_excel("tote_shipment.xlsx")
df

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.79158,-65.68902,23.0,73.40
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.79158,-65.68902,23.0,73.40
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.79158,-65.68902,23.0,73.40
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.79158,-65.68902,23.5,74.30
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.79158,-65.68902,23.0,73.40
...,...,...,...,...,...,...,...,...,...,...,...
130056,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:48:51.273,47.74923,-65.64101,23.1,73.58
130057,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:49:58.699,47.74923,-65.64101,23.5,74.30
130058,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:52:45.173,47.74923,-65.64101,23.0,73.40
130059,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:53:48.228,47.74923,-65.64101,23.0,73.40
130060,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 16:33:25.525,47.74923,-65.64101,24.0,75.20

In [ ]:
df = pd.read_excel("tote_shipment.xlsx")
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628000,47.79158,-65.68902,23,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660000,47.79158,-65.68902,23,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234000,47.79158,-65.68902,23,73.4
4,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172000,47.79158,-65.68902,23.5,74.3

In [ ]:
df.head(10)

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.79158,-65.68902,23.0,73.4
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.79158,-65.68902,23.0,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.79158,-65.68902,23.0,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.79158,-65.68902,23.5,74.3
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.79158,-65.68902,23.0,73.4
5,tote,2,(01)00850027865010(21)0082T0219,DC 2,dock_doors_DC2,379663A695EF,2022-08-03 13:22:09.038,47.79366,-65.75921,25.0,77.0
6,tote,2,(01)00850027865010(21)0082T0219,DC 2,dock_doors_DC2,379663A695EF,2022-08-03 13:26:07.080,47.79366,-65.75921,25.0,77.0
7,tote,2,(01)00850027865010(21)0082T0670,DC 2,dock_doors_DC2,379663A695EF,2022-08-03 10:59:28.892,47.79366,-65.75921,24.5,76.1
8,tote,2,(01)00850027865010(21)0082T0670,DC 2,dock_doors_DC2,2FC8DD79125D,2022-08-03 12:48:11.580,47.79366,-65.75921,25.0,77.0
9,tote,2,(01)00850027865010(21)0082T0670,DC 2,dock_doors_DC2,2FC8DD79125D,2022-08-03 13:02:29.755,47.79366,-65.75921,25.0,77.0

In [ ]:
df.tail(15)

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
130046,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:25:20.159,47.74923,-65.64101,23.0,73.40
130047,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:26:26.282,47.74923,-65.64101,23.0,73.40
130048,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:26:44.664,47.74923,-65.64101,23.0,73.40
130049,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:27:25.019,47.74923,-65.64101,23.0,73.40
130050,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:28:26.441,47.74923,-65.64101,23.0,73.40
130051,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,6AF833197EE3,2022-08-04 12:29:22.255,47.74923,-65.64101,23.0,73.40
130052,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:35:56.100,47.74923,-65.64101,23.5,74.30
130053,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:36:23.724,47.74923,-65.64101,23.5,74.30
130054,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:46:55.310,47.74923,-65.64101,23.0,73.40
130055,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,11977BD156C6,2022-08-04 12:47:48.993,47.74923,-65.64101,23.5,74.30
130056,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:48:51.273,47.74923,-65.64101,23.1,73.58
130057,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:49:58.699,47.74923,-65.64101,23.5,74.30
130058,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:52:45.173,47.74923,-65.64101,23.0,73.40
130059,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:53:48.228,47.74923,-65.64101,23.0,73.40
130060,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 16:33:25.525,47.74923,-65.64101,24.0,75.20

In [ ]:
df_1 = pd.read_excel("tote_shipment.xlsx", header =None).head()
df_1

,0,1,2,3,4,5,6,7,8,9,10
0,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628000,47.79158,-65.68902,23,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660000,47.79158,-65.68902,23,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234000,47.79158,-65.68902,23,73.4
4,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172000,47.79158,-65.68902,23.5,74.3

In [ ]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [ ]:
df = df.rename (columns ={"asset_type"})

In [ ]:
df.shape

(130062, 11)

In [ ]:
df.info

<bound method DataFrame.info of                 0         1                                2      3   \
0       asset_type  asset_id                           tag_id   Site
1             tote         2  (01)00850027865010(21)0082T0219   DC 1
2             tote         2  (01)00850027865010(21)0082T0219   DC 1
3             tote         2  (01)00850027865010(21)0082T0219   DC 1
4             tote         2  (01)00850027865010(21)0082T0219   DC 1
...            ...       ...                              ...    ...
130057        tote       205  (01)00850027865010(21)0082T1137  Store
130058        tote       205  (01)00850027865010(21)0082T1137  Store
130059        tote       205  (01)00850027865010(21)0082T1137  Store
130060        tote       205  (01)00850027865010(21)0082T1137  Store
130061        tote       205  (01)00850027865010(21)0082T1137  Store

                       4             5                           6         7   \
0                    Zone     device_id                    time_est       lat
1          dock_doors_DC1  7F9A8353E973  2022-08-02 11:59:26.628000  47.79158
2          dock_doors_DC1  EC5B0499234F  2022-08-02 12:00:22.660000  47.79158
3          dock_doors_DC1  7F9A8353E973  2022-08-02 12:01:11.234000  47.79158
4          dock_doors_DC1  3D8B2BDB8673  2022-08-02 13:47:58.172000  47.79158
...                   ...           ...                         ...       ...
130057  store_front_Store  26AB1C9A2E41  2022-08-04 12:48:51.273000  47.74923
130058  store_front_Store  26AB1C9A2E41  2022-08-04 12:49:58.699000  47.74923
130059  store_front_Store  26AB1C9A2E41  2022-08-04 12:52:45.173000  47.74923
130060  store_front_Store  26AB1C9A2E41  2022-08-04 12:53:48.228000  47.74923
130061  store_front_Store  26AB1C9A2E41  2022-08-04 16:33:25.525000  47.74923

              8              9              10
0            lng  Temperature_C  Temperature_F
1      -65.68902             23           73.4
2      -65.68902             23           73.4
3      -65.68902             23           73.4
4      -65.68902           23.5           74.3
...          ...            ...            ...
130057 -65.64101           23.1          73.58
130058 -65.64101           23.5           74.3
130059 -65.64101             23           73.4
130060 -65.64101             23           73.4
130061 -65.64101             24           75.2

[130062 rows x 11 columns]>

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10
count,130062,130062,130062,130062,130062,130062,130062,130062.00000,130062.00000,130062.0,130062.0
unique,2,19,35,5,16,39,129888,473.00000,548.00000,973.0,973.0
top,tote,37,(01)00850027865010(21)0082T0953,Store,receiving_Store,AC8DEAE6FD79,2022-08-05 01:04:26.437000,47.74923,-65.64101,24.5,76.1
freq,130061,12841,6602,96897,66099,43611,2,94843.00000,94844.00000,17605.0,17605.0

In [ ]:
from traitlets.traitlets import All
df.describe(include="all")

,0,1,2,3,4,5,6,7,8,9,10
count,130062,130062,130062,130062,130062,130062,130062,130062.00000,130062.00000,130062.0,130062.0
unique,2,19,35,5,16,39,129888,473.00000,548.00000,973.0,973.0
top,tote,37,(01)00850027865010(21)0082T0953,Store,receiving_Store,AC8DEAE6FD79,2022-08-05 01:04:26.437000,47.74923,-65.64101,24.5,76.1
freq,130061,12841,6602,96897,66099,43611,2,94843.00000,94844.00000,17605.0,17605.0

In [ ]:
df= df.rename(columns={})

In [ ]:
df["asset_id"].unique()

KeyError: ignored

In [ ]:
df.tag_id.nunique()

In [ ]:
df.zona.unique()

In [ ]:
df.groupby(["asset_id"])["tag id"],nunique(), reset_index())

In [ ]:
pd.DataFrame(df.groupby(["sitio"])["zona"].nunique()).reset.index()

# New Section