In [ ]:

import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
df = pd.read_csv('movie_review.csv')
df

           id  sentiment                                             review
0      5814_8        1.0  With all this stuff going down at the moment w...
1      2381_9        1.0  \"The Classic War of the Worlds\" by Timothy H...
2      7759_3        0.0  The film starts with a manager (Nicholas Bell)...
3      3630_4        0.0  It must be assumed that those who praised this...
4      9495_8        1.0  Superbly trashy and wondrously unpretentious 8...
...       ...        ...                                                ...
8441   3720_2        0.0  Is this film a joke? Is it a comedy? Surely it...
8442  4229_10        1.0  Don't waste time reading my review. Go out and...
8443   8042_3        0.0  The secret is...this movie blows. Sorry, but i...
8444   9669_9        1.0  After reading the original play I thought it w...
8445  11216_7        1.0  The story is extremely unique.It's about these...

[8446 rows x 3 columns]

In [ ]:
df.describe(include = 'all')

            id    sentiment                                             review
count     8446  8445.000000                                               8445
unique    5001          NaN                                               4999
top     8288_1          NaN  The '60s is an occasionally entertaining film,...
freq         2          NaN                                                  4
mean       NaN     0.504204                                                NaN
std        NaN     0.500012                                                NaN
min        NaN     0.000000                                                NaN
25%        NaN     0.000000                                                NaN
50%        NaN     1.000000                                                NaN
75%        NaN     1.000000                                                NaN
max        NaN     1.000000                                                NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8446 entries, 0 to 8445
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         8446 non-null   object
 1   sentiment  8445 non-null   float64
 2   review     8445 non-null   object
dtypes: float64(1), object(2)
memory usage: 198.1+ KB

In [ ]:
df.shape

(8446, 3)

limpiezas:
de html

pasar todo a minusculas

trimming

reemplazar puntos


sugerencias:
quitar the,signos de puntuacion

In [ ]:
#Limpieza de datos en Python

#1.Escapar caracteres HTML
import HTMLParser
html_parser = HTMLParser.HTMLParser()
texto = html_parser.unescape(original_tweet)

#2.Decodificar los datos
texto = original_tweet.decode("utf8").encode(‘ascii’,’ignore’)

#3.Eliminar palabras comunes
# https://www.ranks.nl/stopwords/spanish
PALABRAS_COMUNES = ["un", "una", "ir", "voy",....]
palabras = texto.split()
reformado = ['' if palabra in PALABRAS_COMUNES else palabra for palabra in palabras]
texto = " ".join(reformado)

#4.Eliminar puntuaciones
# CUIDADO! elimina todo tipo de puntuacion, las comas,
# puntos, signos de admiracion y pregunta pueden ser
# necesarios y no deberían ser eliminados
import string
texto = texto.translate(None, string.punctuation)

#5.Separar palabras pegadas
# transforma AguanteRiver en Aguante River
import re
limpiada = “ ”.join(re.findall(‘[A-Z][^A-Z]*’, texto))

#6.Reemplazar el argot / jerga
JERGA = {"cazas":"entiendes", "LOL":"JAJAJA", "che":"hey",....}
texto = [JERGA[palabra] if palabra in JERGA else palabra for palabra in palabras]

#7.Estandarizar palabras
# frases como "estoy muuuuuy feliz" las convertimos en "estoy muy feliz"
texto = ''.join(''.join(s)[:2] for _, s in itertools.groupby(texto))

#8.Eliminar urls
import re
texto = re.sub(r'^https?:\/\/.*[\r\n]*', '', texto, flags=re.MULTILINE)

#9.Controlar la gramática
# claramente una solución final sería mucho mas complejo que este ejemplo
# recomiendo utilizar alguna herramienta externa para esto
GRAMATICA = {"la nene":"la nena", "el nena":"el nene", "los señor":"el señor",....}
texto = [GRAMATICA [palabra] if palabra in GRAMATICA else palabra for palabra in palabras]

#10.Corregir la sintaxis
# al igual que el punto 9, es mejor utilizar una solucion mas completa
SINTAXIS = {"senor":"señor", "dia":"día",....}
texto = [SINTAXIS [palabra] if palabra in SINTAXIS else palabra for palabra in palabras]